services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./<folder_name>:/var/www/<folder_name>
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/ssl_certificate.cer:/etc/ssl_certificate.cer
      - ./ssl/_private-key.key:/etc/_private-key.key
    depends_on:
      - server
    networks:
      - server
  server: 
    container_name: nodejs_server
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - <container_db>
    links:
      - <container_db>
    networks:
      - server
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=production

networks:
  server:
    driver: bridge